# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration


parameters:
    blog_uploads_directory: '%kernel.project_dir%/public/uploads/blog'
    event_images_directory: '%kernel.project_dir%/public/uploads/events'
    association_images_directory: '%kernel.project_dir%/public/uploads/associations'
    google_client_id: '%env(GOOGLE_CLIENT_ID)%'
    google_client_secret: '%env(GOOGLE_CLIENT_SECRET)%'
    google_redirect_uri: '%env(GOOGLE_REDIRECT_URI)%'
    images_directory: '%kernel.project_dir%/public/uploads'
    imagesProduit_directory: '%kernel.project_dir%/public/uploadsImageProduit'


services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Service\CartService:
        arguments:
            $requestStack: '@request_stack'
            $container: '@service_container'
    App\Service\EmailService:
        arguments:
            $mailer: '@mailer'
    App\Controller\GoogleLoginController:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $passwordHasher: '@security.password_hasher'
            $tokenStorage: '@security.token_storage'
            $eventDispatcher: '@event_dispatcher'
            $googleClientId: '%env(GOOGLE_CLIENT_ID)%'
            $googleClientSecret: '%env(GOOGLE_CLIENT_SECRET)%'
            $googleRedirectUri: '%env(GOOGLE_REDIRECT_URI)%'

    